### ISSUE TITLE
Secure Allele Frequency and Chisq Test 

### ISSUE THREAD

**Issue by lovingmage** [wsasyz/SHIELDSMART#6]
Secure Allele Frequency and Chisq Test 
===

This issue contains the minimum functional interface that can:

- [x] 1. Read downloaded candidate files(assume the files has been downloaded into two folders, case and control folders) and get genotype information for each candidate.
- [x] 2. Perform Allele Frequency computing over the candidate data and output a vcf file that contains all AF results.
- [x] 3. Perform Chi-Square test over the candidate data and output the top 10 records.

**Comment by Leo-ATP** [comment]
This issue has been solved. Close at this time
